(() => {
'use strict';
const {$,$$,icons,mascot,products,questions}=window.BeanoData;
const state={step:0,answers:{},selectedProduct:null,weight:null,review:false};
const widget=$('#widget'),launcher=$('#launcher'),chatScreen=$('#chatScreen'),advisorScreen=$('#advisorScreen'),advisorBody=$('#advisorBody');
const money=v=>`${v.toFixed(2).replace('.',',')} €`; const now=()=>new Date().toLocaleTimeString('sk-SK',{hour:'2-digit',minute:'2-digit'});
function openWidget(){widget.classList.add('open');widget.setAttribute('aria-hidden','false');launcher.style.display='none'}
function closeWidget(){widget.classList.remove('open');widget.setAttribute('aria-hidden','true');launcher.style.display='flex'}
$('#openWidget').onclick=openWidget;$('#launcherLabel').onclick=openWidget;$('#closeWidget').onclick=closeWidget;
function showScreen(name){chatScreen.classList.toggle('active',name==='chat');advisorScreen.classList.toggle('active',name==='advisor');if(name==='advisor')renderAdvisor();}
$('#openAdvisor').onclick=()=>showScreen('advisor');$('#quickAdvisor').onclick=()=>showScreen('advisor');$('#backToChat').onclick=()=>showScreen('chat');
function avatar(){return `<span class="msg-avatar">${icons.brand}</span>`} function msg(text,me=false){return `<div class="msg${me?' me':''}">${me?'':avatar()}<div class="msg-stack"><div class="bubble">${text}</div><span class="time">${now()}</span></div></div>`}
const chatMessages=$('#chatMessages');const quickChips=$('#quickChips');
function initChat(){chatMessages.innerHTML=msg('<b>Ahoj, som Beano.</b> Pomôžem vám vybrať kávu alebo odpoviem na krátku otázku. Výber kávy otvoríte tlačidlom hore.');quickChips.innerHTML=['Káva bez kyslosti','Do automatu','Na cappuccino','Bezkofeínová'].map(t=>`<button type="button">${t}</button>`).join('');quickChips.querySelectorAll('button').forEach(b=>b.onclick=()=>answerChat(b.textContent));}
function answerChat(q){chatMessages.insertAdjacentHTML('beforeend',msg(q,true));quickChips.innerHTML='';chatMessages.insertAdjacentHTML('beforeend',`<div class="msg" id="typing">${avatar()}<div class="bubble typing"><i></i><i></i><i></i></div></div>`);chatMessages.scrollTop=chatMessages.scrollHeight;setTimeout(()=>{const typ=$('#typing');if(typ)typ.remove();let a='Najistejšie bude spustiť krátky výber. Zohľadní prípravu, chuť, mlieko aj kofeín.';const l=q.toLowerCase();if(l.includes('kys'))a='Hľadajte Brazil Santos alebo Cuba Serrano. Obe sú jemné, čokoládové a majú veľmi nízku aciditu.';else if(l.includes('automat'))a='Do automatu býva najbezpečnejší Paganini blend. Je vyvážený, krémový a dobre funguje aj s mliekom.';else if(l.includes('capp'))a='Na cappuccino odporúčam Puccini alebo Paganini. Majú dosť tela, aby ich mlieko neprekrylo.';else if(l.includes('bez'))a='Bezkofeínová Brazil je jemná voľba na večer. Chuťovo zostáva blízko klasickej káve.';chatMessages.insertAdjacentHTML('beforeend',msg(a));chatMessages.insertAdjacentHTML('beforeend',`<div class="msg">${avatar()}<div class="msg-stack"><button class="advisor-cta" style="margin-top:2px" id="chatAdvisor"><span class="cta-icon">${icons.bag}</span><span><b>Spustiť výber kávy</b><span>4 krátke otázky</span></span><span class="arrow">›</span></button></div></div>`);$('#chatAdvisor').onclick=()=>showScreen('advisor');chatMessages.scrollTop=chatMessages.scrollHeight;},650)}
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();const input=$('#chatInput'),v=input.value.trim();if(!v)return;input.value='';answerChat(v)});$('#resetChat').onclick=initChat;
function updateProgress(){const current=Math.min(state.step,3);$('#stepLabel').textContent=state.step<4?`Krok ${state.step+1} zo 4`:(state.selectedProduct?'Vyberte balenie':'Odporúčanie');$('#stepName').textContent=state.step<4?questions[state.step].name:(state.selectedProduct?'Hmotnosť':'Výsledok');$('#progress').innerHTML=Array.from({length:4},(_,i)=>`<i class="${i<current?'done on':i===current?'on':''}"></i>`).join('');$('#prevBtn').style.visibility=state.step===0?'hidden':'visible';}
function renderAdvisor(){updateProgress();if(state.step<4)renderQuestion();else if(!state.selectedProduct)renderResults();else if(state.review)renderOrder();else renderWeights();}
function renderQuestion(){const q=questions[state.step],chosen=state.answers[q.key];advisorBody.innerHTML=`<div class="guide-row"><span class="mascot big">${mascot().replace('class="mascot"','class="mascot big"').replace(/^<span class="mascot big">|<\/span>$/g,'')}</span><div class="guide-bubble"><b>Beano:</b> ${q.guide}</div></div><div class="question-card"><h2>${q.title}</h2><p>${q.help}</p><div class="options">${q.options.map((o,i)=>`<button class="option${chosen===o[0]?' selected':''}${chosen&&chosen!==o[0]?' dimmed':''}" data-value="${o[0]}" style="animation-delay:${i*.05}s"><span class="option-icon">${icons[o[1]]}</span><span><b>${o[2]}</b><small>${o[3]}</small></span><span class="option-state">${chosen===o[0]?icons.check:icons.next}</span></button>`).join('')}</div></div>`;$('#nextBtn').disabled=!chosen;$('#nextBtn').innerHTML=state.step===3?'Zobraziť odporúčanie '+icons.next:'Pokračovať '+icons.next;advisorBody.querySelectorAll('.option').forEach(btn=>btn.onclick=()=>selectOption(btn,q.key));}
function selectOption(btn,key){state.answers[key]=btn.dataset.value;advisorBody.querySelectorAll('.option').forEach(el=>{const selected=el===btn;el.classList.toggle('selected',selected);el.classList.toggle('dimmed',!selected);el.querySelector('.option-state').innerHTML=selected?icons.check:icons.next;});$('#nextBtn').disabled=false;}
$('#nextBtn').onclick=()=>{if(state.step<4){if(!state.answers[questions[state.step].key])return;state.step++;state.selectedProduct=null;state.weight=null;state.review=false;renderAdvisor();advisorBody.scrollTop=0;}else if(state.selectedProduct&&state.weight){state.review=true;renderAdvisor();advisorBody.scrollTop=0;}};
$('#prevBtn').onclick=()=>{if(state.step===4){if(state.review){state.review=false;}else if(state.selectedProduct){state.selectedProduct=null;state.weight=null;}else{state.step=3;}renderAdvisor();advisorBody.scrollTop=0;return;}if(state.step>0){state.step--;renderAdvisor();advisorBody.scrollTop=0;}};
$('#resetAdvisor').onclick=()=>{state.step=0;state.answers={};state.selectedProduct=null;state.weight=null;state.review=false;renderAdvisor()};
function rankProducts(){return products.map(p=>{let score=58;['prep','taste','drink','caffeine'].forEach(k=>{const val=state.answers[k];if((p[k]||[]).includes(val))score+=10;});return {...p,score:Math.min(score,98)}}).sort((a,b)=>b.score-a.score).slice(0,3)}
function renderResults(){const ranked=rankProducts();advisorBody.innerHTML=`<div class="guide-row"><span class="mascot big">${mascot().replace('class="mascot"','class="mascot big"').replace(/^<span class="mascot big">|<\/span>$/g,'')}</span><div class="guide-bubble"><b>Beano:</b> Hotovo. Porovnal som kávy a tieto vám sedia najviac.</div></div><div class="result-intro"><b>Najlepšia zhoda podľa vašich odpovedí</b><span>Vyberte si jednu kávu. Potom zvolíte hmotnosť.</span></div>${ranked.map((p,i)=>`<article class="product-card${i===0?' top':''}"><div class="product-top"><div class="coffee-pack"><div><b>${p.short}</b><span>ROASTED COFFEE</span></div></div><div><h3>${p.name}</h3><p>${p.origin}<br>${p.reason}</p></div><span class="match">${p.score}%</span></div><div class="tags">${p.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><button class="pick-product" data-id="${p.id}">${i===0?'Vybrať najlepšiu zhodu':'Vybrať túto kávu'}</button></article>`).join('')}`;$('#nextBtn').disabled=true;$('#nextBtn').style.display='none';advisorBody.querySelectorAll('.pick-product').forEach(b=>b.onclick=()=>{state.selectedProduct=products.find(p=>p.id===b.dataset.id);state.weight=null;state.review=false;renderAdvisor();advisorBody.scrollTop=0;});}
function renderWeights(){const p=state.selectedProduct;advisorBody.innerHTML=`<div class="guide-row"><span class="mascot big">${mascot().replace('class="mascot"','class="mascot big"').replace(/^<span class="mascot big">|<\/span>$/g,'')}</span><div class="guide-bubble"><b>Beano:</b> Dobrá voľba. Teraz už iba veľkosť balenia.</div></div><div class="weight-title"><h2>Koľko kávy chcete?</h2><p>${p.name} · zvoľte balenie podľa spotreby</p></div><div class="weights">${[250,500,1000].map(w=>`<button class="weight${state.weight===w?' selected':''}" data-weight="${w}">${w===500?'<span class="popular">Najčastejšia voľba</span>':''}<span class="weight-bag"></span><b>${w===1000?'1 kg':w+' g'}</b><small>${money(p.price[w])}</small></button>`).join('')}</div><div class="order-summary" id="weightSummary"><div class="sum-row"><span>Káva</span><b>${p.name}</b></div><div class="sum-row"><span>Balenie</span><b id="sumWeight">—</b></div><div class="sum-row total"><span>Spolu</span><b id="sumPrice">—</b></div></div>`;$('#nextBtn').style.display='inline-flex';$('#nextBtn').innerHTML='Pokračovať '+icons.next;$('#nextBtn').disabled=!state.weight;advisorBody.querySelectorAll('.weight').forEach(b=>b.onclick=()=>{state.weight=Number(b.dataset.weight);advisorBody.querySelectorAll('.weight').forEach(x=>x.classList.toggle('selected',x===b));$('#sumWeight').textContent=state.weight===1000?'1 kg':state.weight+' g';$('#sumPrice').textContent=money(p.price[state.weight]);$('#nextBtn').disabled=false;});}
function renderOrder(){const p=state.selectedProduct,w=state.weight;advisorBody.innerHTML=`<div class="guide-row"><span class="mascot big">${mascot().replace('class="mascot"','class="mascot big"').replace(/^<span class="mascot big">|<\/span>$/g,'')}</span><div class="guide-bubble"><b>Beano:</b> Skontrolujte výber. Potom ho vložíme do košíka.</div></div><div class="weight-title"><h2>Váš výber je pripravený</h2><p>Presne podľa vašej prípravy a chuti.</p></div><div class="order-summary"><div class="sum-row"><span>Káva</span><b>${p.name}</b></div><div class="sum-row"><span>Balenie</span><b>${w===1000?'1 kg':w+' g'}</b></div><div class="sum-row"><span>Chuť</span><b>${p.tags.slice(0,2).join(' · ')}</b></div><div class="sum-row total"><span>Spolu</span><b>${money(p.price[w])}</b></div></div><button class="order-btn" id="orderBtn">Pridať do košíka</button>`;$('#nextBtn').style.display='none';$('#orderBtn').onclick=completeOrder;}
function completeOrder(){const p=state.selectedProduct,w=state.weight;advisorBody.innerHTML=`<div class="success-card"><div class="success-icon">✓</div><h2>Pridané do košíka</h2><p>${p.name}, ${w===1000?'1 kg':w+' g'} za ${money(p.price[w])}. V reálnom e-shope by sa teraz otvoril košík.</p><button class="order-btn" id="backChatSuccess">Späť do chatu</button></div>`;$('#nextBtn').style.display='none';$('#prevBtn').style.visibility='hidden';$('#backChatSuccess').onclick=()=>{showScreen('chat');chatMessages.insertAdjacentHTML('beforeend',msg(`Vybral som pre vás <b>${p.name}</b>, balenie ${w===1000?'1 kg':w+' g'}.`,false));chatMessages.scrollTop=chatMessages.scrollHeight;};}
initChat();renderAdvisor();
})();
