/* Verified official shop products; see research/catalogue-expansion-2026-10-09.json. */
globalThis.CX_CATALOGUES = {
  "mylo": {
    "verifiedAt": "2026-10-09T20:40:07.129505+00:00",
    "products": [
      {
        "id": "catalogue-5271",
        "name": "LIPOVÁ VODA",
        "url": "https://www.mylo.sk/lipova-kozmetika/lipova-voda/",
        "priceAmount": 20.0,
        "currency": "EUR",
        "price": "20,00 €",
        "volume": "100ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové vody a tonery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky pleťové vody a tonery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-5271.webp"
      },
      {
        "id": "catalogue-4032",
        "name": "Čistiaci gél HARMÓNIA",
        "url": "https://www.mylo.sk/starostlivost-o-tvar/harmonia/",
        "priceAmount": 18.0,
        "currency": "EUR",
        "price": "18,00 €",
        "volume": "100ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Čistenie a odličovanie",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky čistenie a odličovanie. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-4032.webp"
      },
      {
        "id": "catalogue-2553",
        "name": "Ílové mydlo CÉDROVÁ RUŽA (bezobalové)",
        "url": "https://www.mylo.sk/starostlivost-o-telo/cedrova-ruza/",
        "priceAmount": 5.9,
        "currency": "EUR",
        "price": "5,90 €",
        "volume": "100g",
        "variantLabel": "",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-2553.webp"
      },
      {
        "id": "catalogue-2463",
        "name": "Pílingové mydlo ŽIENKA DOMÁCA (bezobalové)",
        "url": "https://www.mylo.sk/starostlivost-o-telo/zienka-domaca/",
        "priceAmount": 5.9,
        "currency": "EUR",
        "price": "5,90 €",
        "volume": "100g",
        "variantLabel": "",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-2463.webp"
      },
      {
        "id": "catalogue-1498",
        "name": "Odličovací gél HERBÁRIUM",
        "url": "https://www.mylo.sk/starostlivost-o-tvar/prirodny-odlicovac/?attribute_pa_obal=s-pumpickou",
        "priceAmount": 28.0,
        "currency": "EUR",
        "price": "28,00 €",
        "volume": "150ml",
        "variantLabel": "s-pumpickou",
        "category": "face",
        "kind": "Čistenie a odličovanie",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry"
        ],
        "reason": "Z ponuky čistenie a odličovanie. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-1498.webp"
      },
      {
        "id": "catalogue-981",
        "name": "Tuhý prírodný dezodorant MÄTOVÁ FIALKA",
        "url": "https://www.mylo.sk/starostlivost-o-telo/matova-fialka/",
        "priceAmount": 12.0,
        "currency": "EUR",
        "price": "12,00 €",
        "volume": "40g",
        "variantLabel": "",
        "category": "body",
        "kind": "Dezodoranty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry"
        ],
        "reason": "Z ponuky dezodoranty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-981.webp"
      },
      {
        "id": "catalogue-976",
        "name": "Olej na bradu TARAS BUĽBA",
        "url": "https://www.mylo.sk/panska-kozmetika/taras-bulba/",
        "priceAmount": 12.0,
        "currency": "EUR",
        "price": "12,00 €",
        "volume": "30ml",
        "variantLabel": "",
        "category": "beard",
        "kind": "Oleje na bradu",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky oleje na bradu. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-976.webp"
      },
      {
        "id": "catalogue-960",
        "name": "Hydratačné sérum INOVAŤ",
        "url": "https://www.mylo.sk/starostlivost-o-tvar/inovat/",
        "priceAmount": 19.0,
        "currency": "EUR",
        "price": "19,00 €",
        "volume": "20ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové séra",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "balanced",
          "hydrate",
          "serum"
        ],
        "reason": "Z ponuky pleťové séra. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-960.webp"
      },
      {
        "id": "catalogue-880",
        "name": "Balzam na bradu KAPITÁN",
        "url": "https://www.mylo.sk/panska-kozmetika/kapitan-balzam/",
        "priceAmount": 11.7,
        "currency": "EUR",
        "price": "11,70 €",
        "volume": "30ml",
        "variantLabel": "",
        "category": "beard",
        "kind": "Balzamy na bradu",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate",
          "cream",
          "simple"
        ],
        "reason": "Z ponuky balzamy na bradu. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-880.webp"
      },
      {
        "id": "catalogue-871",
        "name": "pleťový olej OLIVÍN",
        "url": "https://www.mylo.sk/starostlivost-o-tvar/olivin/?attribute_pa_objem=15ml",
        "priceAmount": 13.5,
        "currency": "EUR",
        "price": "13,50 €",
        "volume": "15ml",
        "variantLabel": "15ml",
        "category": "face",
        "kind": "Pleťové oleje",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "balanced",
          "mature",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky pleťové oleje. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-871.webp"
      },
      {
        "id": "catalogue-815",
        "name": "Pleťový krém RUŽA A GRANÁTOVÉ JABLKO",
        "url": "https://www.mylo.sk/starostlivost-o-tvar/ruza-a-granatove-jablko/?attribute_pa_objem=50ml",
        "priceAmount": 27.0,
        "currency": "EUR",
        "price": "27,00 €",
        "volume": "50ml",
        "variantLabel": "50ml",
        "category": "face",
        "kind": "Pleťové krémy",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive",
          "hydrate",
          "mature",
          "cream",
          "simple"
        ],
        "reason": "Z ponuky pleťové krémy. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-815.webp"
      },
      {
        "id": "catalogue-755",
        "name": "Olej na bradu KAPITÁN",
        "url": "https://www.mylo.sk/panska-kozmetika/kapitan/?attribute_pa_objem=30ml",
        "priceAmount": 12.0,
        "currency": "EUR",
        "price": "12,00 €",
        "volume": "30ml",
        "variantLabel": "30ml",
        "category": "beard",
        "kind": "Oleje na bradu",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate",
          "mature",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky oleje na bradu. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-755.webp"
      },
      {
        "id": "catalogue-748",
        "name": "Olej na bradu LOKTIBRADA",
        "url": "https://www.mylo.sk/panska-kozmetika/loktibrada/?attribute_pa_objem=30ml",
        "priceAmount": 12.0,
        "currency": "EUR",
        "price": "12,00 €",
        "volume": "30ml",
        "variantLabel": "30ml",
        "category": "beard",
        "kind": "Oleje na bradu",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky oleje na bradu. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-748.webp"
      },
      {
        "id": "catalogue-696",
        "name": "Pleťový olej na mastnú a aknóznu pleť AKO VÁNOK",
        "url": "https://www.mylo.sk/starostlivost-o-tvar/ako-vanok/?attribute_pa_objem=15ml",
        "priceAmount": 12.0,
        "currency": "EUR",
        "price": "12,00 €",
        "volume": "15ml",
        "variantLabel": "15ml",
        "category": "face",
        "kind": "Pleťové oleje",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky pleťové oleje. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-696.webp"
      },
      {
        "id": "catalogue-687",
        "name": "Krém z bambuckého masla OH LA LA!",
        "url": "https://www.mylo.sk/starostlivost-o-tvar/oh-la-la/?attribute_pa_objem=60ml",
        "priceAmount": 9.5,
        "currency": "EUR",
        "price": "9,50 €",
        "volume": "60ml",
        "variantLabel": "60ml",
        "category": "baby",
        "kind": "Starostlivosť o deti a mamy",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky starostlivosť o deti a mamy. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-687.webp"
      },
      {
        "id": "catalogue-628",
        "name": "Tuhý šampón VIETOR",
        "url": "https://www.mylo.sk/starostlivost-o-vlasy/tuhy-sampon/",
        "priceAmount": 10.0,
        "currency": "EUR",
        "price": "10,00 €",
        "volume": "60g",
        "variantLabel": "",
        "category": "hair",
        "kind": "Šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive",
          "hydrate"
        ],
        "reason": "Z ponuky šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-628.webp"
      },
      {
        "id": "catalogue-569",
        "name": "Pleťový olej PREBUDENIE",
        "url": "https://www.mylo.sk/starostlivost-o-tvar/prebudenie/?attribute_pa_objem=15ml",
        "priceAmount": 12.0,
        "currency": "EUR",
        "price": "12,00 €",
        "volume": "15ml",
        "variantLabel": "15ml",
        "category": "face",
        "kind": "Pleťové oleje",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "balanced",
          "hydrate",
          "calm",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky pleťové oleje. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-569.webp"
      },
      {
        "id": "catalogue-543",
        "name": "Pleťový olej FLÓRA",
        "url": "https://www.mylo.sk/starostlivost-o-tvar/flora/?attribute_pa_objem=50ml",
        "priceAmount": 24.0,
        "currency": "EUR",
        "price": "24,00 €",
        "volume": "50ml",
        "variantLabel": "50ml",
        "category": "face",
        "kind": "Pleťové oleje",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive",
          "hydrate",
          "mature",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky pleťové oleje. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-543.webp"
      },
      {
        "id": "catalogue-531",
        "name": "Čistiaca maska na mastnú pleť LÁVA",
        "url": "https://www.mylo.sk/starostlivost-o-tvar/lava/",
        "priceAmount": 16.0,
        "currency": "EUR",
        "price": "16,00 €",
        "volume": "50g",
        "variantLabel": "",
        "category": "face",
        "kind": "Čistenie a odličovanie",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "balanced",
          "hydrate"
        ],
        "reason": "Z ponuky čistenie a odličovanie. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-531.webp"
      },
      {
        "id": "catalogue-525",
        "name": "Prírodný detský balzam na zapareniny LUNA",
        "url": "https://www.mylo.sk/detska-kozmetika/luna/",
        "priceAmount": 11.0,
        "currency": "EUR",
        "price": "11,00 €",
        "volume": "30ml",
        "variantLabel": "",
        "category": "baby",
        "kind": "Starostlivosť o deti a mamy",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "calm",
          "cream",
          "simple"
        ],
        "reason": "Z ponuky starostlivosť o deti a mamy. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-525.webp"
      },
      {
        "id": "catalogue-519",
        "name": "Krém na nohy NOHY BOSÉ",
        "url": "https://www.mylo.sk/starostlivost-o-telo/nohy-bose/",
        "priceAmount": 12.0,
        "currency": "EUR",
        "price": "12,00 €",
        "volume": "60ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Telové krémy a maslá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate"
        ],
        "reason": "Z ponuky telové krémy a maslá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-519.webp"
      },
      {
        "id": "catalogue-516",
        "name": "Krém z bambuckého masla TROJRUŽA",
        "url": "https://www.mylo.sk/starostlivost-o-tvar/trojruza-2/",
        "priceAmount": 9.5,
        "currency": "EUR",
        "price": "9,50 €",
        "volume": "60ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Telové krémy a maslá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky telové krémy a maslá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-516.webp"
      },
      {
        "id": "catalogue-509",
        "name": "Balzam na bradu ŠUHAJ",
        "url": "https://www.mylo.sk/panska-kozmetika/suhaj/",
        "priceAmount": 13.5,
        "currency": "EUR",
        "price": "13,50 €",
        "volume": "30ml",
        "variantLabel": "",
        "category": "beard",
        "kind": "Balzamy na bradu",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate",
          "cream",
          "simple"
        ],
        "reason": "Z ponuky balzamy na bradu. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-509.webp"
      },
      {
        "id": "catalogue-503",
        "name": "Intímny umývací gél LADA",
        "url": "https://www.mylo.sk/starostlivost-o-telo/lada/",
        "priceAmount": 24.0,
        "currency": "EUR",
        "price": "24,00 €",
        "volume": "150ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Umývanie",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "calm"
        ],
        "reason": "Z ponuky umývanie. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-503.webp"
      },
      {
        "id": "catalogue-490",
        "name": "Masážny olej NEŽNOSŤ",
        "url": "https://www.mylo.sk/starostlivost-o-telo/neznost/",
        "priceAmount": 14.0,
        "currency": "EUR",
        "price": "14,00 €",
        "volume": "50ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Telové oleje",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry"
        ],
        "reason": "Z ponuky telové oleje. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-490.webp"
      },
      {
        "id": "catalogue-481",
        "name": "Pleťová voda KVETOVÁ ROSA",
        "url": "https://www.mylo.sk/starostlivost-o-tvar/kvetova-rosa/",
        "priceAmount": 22.0,
        "currency": "EUR",
        "price": "22,00 €",
        "volume": "100ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové vody a tonery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate",
          "calm",
          "mature"
        ],
        "reason": "Z ponuky pleťové vody a tonery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-481.webp"
      },
      {
        "id": "catalogue-467",
        "name": "Odličovací olej BOTANIKA",
        "url": "https://www.mylo.sk/starostlivost-o-tvar/botanika/",
        "priceAmount": 20.0,
        "currency": "EUR",
        "price": "20,00 €",
        "volume": "100ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Čistenie a odličovanie",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "sensitive",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky čistenie a odličovanie. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-467.webp"
      },
      {
        "id": "catalogue-464",
        "name": "Čistiace a odličovacie mlieko MOISSANIT",
        "url": "https://www.mylo.sk/starostlivost-o-tvar/moissanit/",
        "priceAmount": 20.0,
        "currency": "EUR",
        "price": "20,00 €",
        "volume": "200ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Čistenie a odličovanie",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive",
          "hydrate"
        ],
        "reason": "Z ponuky čistenie a odličovanie. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-464.webp"
      },
      {
        "id": "catalogue-457",
        "name": "Pílingové mydlo LEVANDUĽOVÁ VANILKA",
        "url": "https://www.mylo.sk/starostlivost-o-telo/levandulova-vanilka/?attribute_pa_obal=bez-obalu",
        "priceAmount": 6.5,
        "currency": "EUR",
        "price": "6,50 €",
        "volume": "100g",
        "variantLabel": "bez-obalu",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-457.webp"
      },
      {
        "id": "catalogue-448",
        "name": "Soľné mydlo SOĽ NAD ZLATO",
        "url": "https://www.mylo.sk/starostlivost-o-telo/sol-nad-zlato/?attribute_pa_obal=bez-obalu",
        "priceAmount": 5.5,
        "currency": "EUR",
        "price": "5,50 €",
        "volume": "100g",
        "variantLabel": "bez-obalu",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "hydrate"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-448.webp"
      },
      {
        "id": "catalogue-441",
        "name": "Mydlo na citlivú pokožku AVOKÁDOVÁ OLIVA",
        "url": "https://www.mylo.sk/starostlivost-o-telo/avokadova-oliva/?attribute_pa_obal=bez-obalu",
        "priceAmount": 5.0,
        "currency": "EUR",
        "price": "5,00 €",
        "volume": "100g",
        "variantLabel": "bez-obalu",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive",
          "hydrate"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-441.webp"
      },
      {
        "id": "catalogue-434",
        "name": "Nechtíkové mydlo na suchú pokožku SLNKO V SIETI",
        "url": "https://www.mylo.sk/starostlivost-o-telo/slnko-v-sieti/?attribute_pa_obal=bez-obalu",
        "priceAmount": 5.0,
        "currency": "EUR",
        "price": "5,00 €",
        "volume": "100g",
        "variantLabel": "bez-obalu",
        "category": "body",
        "kind": "Nechty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky nechty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-434.webp"
      },
      {
        "id": "catalogue-423",
        "name": "Uhlíkové mydlo na mastnú pleť a akné ČIERNA OVCA",
        "url": "https://www.mylo.sk/starostlivost-o-tvar/cierna-ovca/?attribute_pa_obal=bez-obalu",
        "priceAmount": 5.0,
        "currency": "EUR",
        "price": "5,00 €",
        "volume": "100g",
        "variantLabel": "bez-obalu",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "hydrate"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/mylo-catalogue-423.webp"
      }
    ]
  },
  "ponio": {
    "verifiedAt": "2026-10-09T20:40:07.129505+00:00",
    "products": [
      {
        "id": "catalogue-10823913636174",
        "name": "Tymianová voda Hanus 250ml",
        "url": "https://ponio.sk/products/tymianova-voda-hanus-250ml?variant=55098656129358",
        "priceAmount": 9.16,
        "currency": "EUR",
        "price": "9,16 €",
        "volume": "250ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové vody a tonery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate"
        ],
        "reason": "Z ponuky pleťové vody a tonery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-10823913636174.webp"
      },
      {
        "id": "catalogue-9824330187086",
        "name": "Mint - suchý šampón",
        "url": "https://ponio.sk/products/suchy-sampon-mint?variant=49661403136334",
        "priceAmount": 7.7,
        "currency": "EUR",
        "price": "7,70 €",
        "volume": "40g",
        "variantLabel": "",
        "category": "hair",
        "kind": "Suché šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "hydrate"
        ],
        "reason": "Z ponuky suché šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-9824330187086.webp"
      },
      {
        "id": "catalogue-9801757688142",
        "name": "Lumina shield – denný ochranný pleťový krém",
        "url": "https://ponio.sk/products/lumina-shield-pletovy-krem?variant=49548618531150",
        "priceAmount": 25.3,
        "currency": "EUR",
        "price": "25,30 €",
        "volume": "50g",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové krémy",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate",
          "mature",
          "cream",
          "simple"
        ],
        "reason": "Z ponuky pleťové krémy. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-9801757688142.webp"
      },
      {
        "id": "catalogue-8702567645518",
        "name": "Banán & kokos - suchý šampón",
        "url": "https://ponio.sk/products/suchy-sampon-banan-kokos?variant=47547206173006",
        "priceAmount": 7.7,
        "currency": "EUR",
        "price": "7,70 €",
        "volume": "40g",
        "variantLabel": "",
        "category": "hair",
        "kind": "Suché šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "hydrate"
        ],
        "reason": "Z ponuky suché šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-8702567645518.webp"
      },
      {
        "id": "catalogue-222802401",
        "name": "Vanilka & kokos - výživný univerzálny pleťový krém",
        "url": "https://ponio.sk/products/vanilka-a-kokos-pletovy-krem?variant=498563425",
        "priceAmount": 13.0,
        "currency": "EUR",
        "price": "13,00 €",
        "volume": "50g",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové krémy",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "sensitive",
          "balanced",
          "hydrate",
          "calm",
          "cream",
          "simple"
        ],
        "reason": "Z ponuky pleťové krémy. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-222802401.webp"
      },
      {
        "id": "catalogue-8593661100366",
        "name": "Healthy aging - pleťový krém pre zrelú pleť",
        "url": "https://ponio.sk/products/healthy-aging-pletovy-krem?variant=47226900709710",
        "priceAmount": 25.3,
        "currency": "EUR",
        "price": "25,30 €",
        "volume": "50g",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové krémy",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate",
          "mature",
          "cream",
          "simple"
        ],
        "reason": "Z ponuky pleťové krémy. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-8593661100366.webp"
      },
      {
        "id": "catalogue-8556380225870",
        "name": "Face & intim bar - santal & bergamot",
        "url": "https://ponio.sk/products/santal-bergamot-face-intim-bar-1?variant=47126799221070",
        "priceAmount": 9.55,
        "currency": "EUR",
        "price": "9,55 €",
        "volume": "50g",
        "variantLabel": "",
        "category": "body",
        "kind": "Umývanie",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive",
          "balanced",
          "hydrate",
          "calm",
          "mature"
        ],
        "reason": "Z ponuky umývanie. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-8556380225870.webp"
      },
      {
        "id": "catalogue-8559034958158",
        "name": "Face & intim bar - tea tree & cajeput",
        "url": "https://ponio.sk/products/tea-tree-cajeput-face-intim-bar?variant=47132152693070",
        "priceAmount": 9.55,
        "currency": "EUR",
        "price": "9,55 €",
        "volume": "50g",
        "variantLabel": "",
        "category": "body",
        "kind": "Umývanie",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "sensitive",
          "balanced",
          "hydrate"
        ],
        "reason": "Z ponuky umývanie. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-8559034958158.webp"
      },
      {
        "id": "catalogue-8544943866190",
        "name": "Face & intim bar sensitive - chamomile",
        "url": "https://ponio.sk/products/chamomile-face-intim-bar-sensitive?variant=47099777515854",
        "priceAmount": 9.55,
        "currency": "EUR",
        "price": "9,55 €",
        "volume": "50g",
        "variantLabel": "",
        "category": "body",
        "kind": "Umývanie",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky umývanie. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-8544943866190.webp"
      },
      {
        "id": "catalogue-8355414671694",
        "name": "Levanduľová voda Hanus 250ml",
        "url": "https://ponio.sk/products/levandulova-voda-hanus?variant=46453628862798",
        "priceAmount": 7.6,
        "currency": "EUR",
        "price": "7,60 €",
        "volume": "250ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové vody a tonery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "sensitive",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky pleťové vody a tonery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-8355414671694.webp"
      },
      {
        "id": "catalogue-8355413459278",
        "name": "Ružová voda Hanus 250ml",
        "url": "https://ponio.sk/products/ruzova-voda-hanus?variant=46453617951054",
        "priceAmount": 9.25,
        "currency": "EUR",
        "price": "9,25 €",
        "volume": "250ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové vody a tonery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky pleťové vody a tonery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-8355413459278.webp"
      },
      {
        "id": "catalogue-7104378110067",
        "name": "Candy mafia - tuhý kondicionér",
        "url": "https://ponio.sk/products/candy-mafia-tuhy-kondicioner?variant=40727603249267",
        "priceAmount": 10.5,
        "currency": "EUR",
        "price": "10,50 €",
        "volume": "50g",
        "variantLabel": "",
        "category": "hair",
        "kind": "Kondicionéry",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate"
        ],
        "reason": "Z ponuky kondicionéry. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-7104378110067.webp"
      },
      {
        "id": "catalogue-7104375947379",
        "name": "Banán & kokos - tuhý kondicionér",
        "url": "https://ponio.sk/products/banan-kokos-tuhy-kondicioner?variant=40727602364531",
        "priceAmount": 10.5,
        "currency": "EUR",
        "price": "10,50 €",
        "volume": "50g",
        "variantLabel": "",
        "category": "hair",
        "kind": "Kondicionéry",
        "tags": [
          "any",
          "basic",
          "full",
          "target"
        ],
        "reason": "Z ponuky kondicionéry. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-7104375947379.webp"
      },
      {
        "id": "catalogue-7047118684275",
        "name": "Lavandin - tuhý kondicionér",
        "url": "https://ponio.sk/products/lavandin-tuhy-kondicioner?variant=40592525262963",
        "priceAmount": 10.5,
        "currency": "EUR",
        "price": "10,50 €",
        "volume": "50g",
        "variantLabel": "",
        "category": "hair",
        "kind": "Kondicionéry",
        "tags": [
          "any",
          "basic",
          "full",
          "target"
        ],
        "reason": "Z ponuky kondicionéry. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-7047118684275.webp"
      },
      {
        "id": "catalogue-7047119765619",
        "name": "Citrón & rozmarín - tuhý kondicionér",
        "url": "https://ponio.sk/products/citron-rozmarin-tuhy-kondicioner?variant=40592534208627",
        "priceAmount": 10.5,
        "currency": "EUR",
        "price": "10,50 €",
        "volume": "50g",
        "variantLabel": "",
        "category": "hair",
        "kind": "Kondicionéry",
        "tags": [
          "any",
          "basic",
          "full",
          "target"
        ],
        "reason": "Z ponuky kondicionéry. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-7047119765619.webp"
      },
      {
        "id": "catalogue-6569548841075",
        "name": "Pink obnova & ochrana - šampúch",
        "url": "https://ponio.sk/products/pink-obnova-ochrana-sampuch-30g-60g?variant=39307027382387",
        "priceAmount": 4.8,
        "currency": "EUR",
        "price": "4,80 €",
        "volume": "30 g",
        "variantLabel": "30 g",
        "category": "hair",
        "kind": "Šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-6569548841075.webp"
      },
      {
        "id": "catalogue-4573959192691",
        "name": "Mint obnova & ochrana - šampúch",
        "url": "https://ponio.sk/products/mint-obnova-ochrana-sampuch-30g-60g?variant=31992613044339",
        "priceAmount": 4.8,
        "currency": "EUR",
        "price": "4,80 €",
        "volume": "30 g",
        "variantLabel": "30 g",
        "category": "hair",
        "kind": "Šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-4573959192691.webp"
      },
      {
        "id": "catalogue-4515552166003",
        "name": "Pink - prírodný deodorant, sodafree",
        "url": "https://ponio.sk/products/pink-prirodny-deodorant-sodafree?variant=31755749064819",
        "priceAmount": 9.3,
        "currency": "EUR",
        "price": "9,30 €",
        "volume": "50ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Dezodoranty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky dezodoranty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-4515552166003.webp"
      },
      {
        "id": "catalogue-4299136172147",
        "name": "Citrus - prírodný deodorant, sodafree",
        "url": "https://ponio.sk/products/citrus-prirodny-deodorant-sodafree?variant=30974692196467",
        "priceAmount": 9.3,
        "currency": "EUR",
        "price": "9,30 €",
        "volume": "50ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Dezodoranty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate"
        ],
        "reason": "Z ponuky dezodoranty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-4299136172147.webp"
      },
      {
        "id": "catalogue-4299132338291",
        "name": "Lavandin - prírodný deodorant, sodafree",
        "url": "https://ponio.sk/products/lavandin-prirodny-deodorant-sodafree?variant=30974548344947",
        "priceAmount": 9.3,
        "currency": "EUR",
        "price": "9,30 €",
        "volume": "50ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Dezodoranty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "sensitive",
          "hydrate"
        ],
        "reason": "Z ponuky dezodoranty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-4299132338291.webp"
      },
      {
        "id": "catalogue-4294804177011",
        "name": "Lemongras - prírodný deodorant, sodafree",
        "url": "https://ponio.sk/products/lemongras-prirodny-deodorant-sodafree?variant=30937147867251",
        "priceAmount": 9.3,
        "currency": "EUR",
        "price": "9,30 €",
        "volume": "50ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Dezodoranty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "sensitive",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky dezodoranty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-4294804177011.webp"
      },
      {
        "id": "catalogue-4293042667635",
        "name": "Mint - prírodný deodorant, sodafree",
        "url": "https://ponio.sk/products/mint-prirodny-deodorant-sodafree?variant=30924792594547",
        "priceAmount": 9.3,
        "currency": "EUR",
        "price": "9,30 €",
        "volume": "50ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Dezodoranty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate"
        ],
        "reason": "Z ponuky dezodoranty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-4293042667635.webp"
      },
      {
        "id": "catalogue-2047692406899",
        "name": "Levanduľa & tea tree - šampúch proti lupinám",
        "url": "https://ponio.sk/products/levandula-tea-tree-sampuch-proti-lupinam-30g-60g?variant=18608526393459",
        "priceAmount": 4.8,
        "currency": "EUR",
        "price": "4,80 €",
        "volume": "30 g",
        "variantLabel": "30 g",
        "category": "hair",
        "kind": "Šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-2047692406899.webp"
      },
      {
        "id": "catalogue-1230939619443",
        "name": "Vanilka & kokos - tyčinka na pery",
        "url": "https://ponio.sk/products/vanilka-kokos-tycinka-na-pery?variant=12669084008563",
        "priceAmount": 7.4,
        "currency": "EUR",
        "price": "7,40 €",
        "volume": "9 ml",
        "variantLabel": "",
        "category": "lips",
        "kind": "Balzamy na pery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "sensitive",
          "hydrate",
          "calm",
          "mature"
        ],
        "reason": "Z ponuky balzamy na pery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-1230939619443.webp"
      },
      {
        "id": "catalogue-1222890422387",
        "name": "Mango zázvor - tyčinka na pery",
        "url": "https://ponio.sk/products/mango-zazvor-tycinka-na-pery?variant=12551979597939",
        "priceAmount": 7.4,
        "currency": "EUR",
        "price": "7,40 €",
        "volume": "9 ml",
        "variantLabel": "",
        "category": "lips",
        "kind": "Balzamy na pery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky balzamy na pery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-1222890422387.webp"
      },
      {
        "id": "catalogue-1215289393267",
        "name": "Melón - tyčinka na pery",
        "url": "https://ponio.sk/products/melon-tycinka-na-pery?variant=12434389041267",
        "priceAmount": 7.4,
        "currency": "EUR",
        "price": "7,40 €",
        "volume": "9 ml",
        "variantLabel": "",
        "category": "lips",
        "kind": "Balzamy na pery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky balzamy na pery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-1215289393267.webp"
      },
      {
        "id": "catalogue-1206693789811",
        "name": "Mäta & pomaranč - tyčinka na pery",
        "url": "https://ponio.sk/products/mata-pomaranc-tycinka-na-pery?variant=12317728833651",
        "priceAmount": 7.4,
        "currency": "EUR",
        "price": "7,40 €",
        "volume": "9 ml",
        "variantLabel": "",
        "category": "lips",
        "kind": "Balzamy na pery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky balzamy na pery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-1206693789811.webp"
      },
      {
        "id": "catalogue-8903726409",
        "name": "Levanduľa & chmeľ - prírodný kondicionér",
        "url": "https://ponio.sk/products/levandula-chmel-prirodny-kondicioner?variant=31210982089",
        "priceAmount": 13.5,
        "currency": "EUR",
        "price": "13,50 €",
        "volume": "100ml",
        "variantLabel": "",
        "category": "hair",
        "kind": "Kondicionéry",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "balanced",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky kondicionéry. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-8903726409.webp"
      },
      {
        "id": "catalogue-217984721",
        "name": "Pomaranč & eukalyptus - prírodný deodorant",
        "url": "https://ponio.sk/products/pomaranc-a-eukalyptus-prirodny-dezodorant?variant=490260393",
        "priceAmount": 9.3,
        "currency": "EUR",
        "price": "9,30 €",
        "volume": "50ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Dezodoranty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky dezodoranty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-217984721.webp"
      },
      {
        "id": "catalogue-3373151813",
        "name": "Tea tree & lemongras - šampúch proti lupinám",
        "url": "https://ponio.sk/products/tea-tree-lemongras-sampuch-proti-lupinam-30g-60g?variant=9902759813",
        "priceAmount": 4.8,
        "currency": "EUR",
        "price": "4,80 €",
        "volume": "30 g",
        "variantLabel": "30 g",
        "category": "hair",
        "kind": "Šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate"
        ],
        "reason": "Z ponuky šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-3373151813.webp"
      },
      {
        "id": "catalogue-2914359493",
        "name": "Orient chai - šampúch proti lupinám",
        "url": "https://ponio.sk/products/orient-chai-sampuch-proti-lupinam-30g-60g?variant=8568488133",
        "priceAmount": 4.8,
        "currency": "EUR",
        "price": "4,80 €",
        "volume": "30 g",
        "variantLabel": "30 g",
        "category": "hair",
        "kind": "Šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate"
        ],
        "reason": "Z ponuky šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-2914359493.webp"
      },
      {
        "id": "catalogue-2659425797",
        "name": "Candy mafia - prírodný kondicionér",
        "url": "https://ponio.sk/products/candy-mafia-prirodny-kondicioner?variant=7754030597",
        "priceAmount": 13.5,
        "currency": "EUR",
        "price": "13,50 €",
        "volume": "100ml",
        "variantLabel": "",
        "category": "hair",
        "kind": "Kondicionéry",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "balanced",
          "hydrate"
        ],
        "reason": "Z ponuky kondicionéry. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-2659425797.webp"
      },
      {
        "id": "catalogue-2655848069",
        "name": "Svieže bylinky - prírodný kondicionér",
        "url": "https://ponio.sk/products/svieze-bylinky-prirodny-kondicioner?variant=7745578693",
        "priceAmount": 13.5,
        "currency": "EUR",
        "price": "13,50 €",
        "volume": "100ml",
        "variantLabel": "",
        "category": "hair",
        "kind": "Kondicionéry",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "balanced",
          "hydrate"
        ],
        "reason": "Z ponuky kondicionéry. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-2655848069.webp"
      },
      {
        "id": "catalogue-2654038213",
        "name": "Orient chai - prírodný kondicionér",
        "url": "https://ponio.sk/products/orient-chai-prirodny-kondicioner?variant=7735642885",
        "priceAmount": 13.5,
        "currency": "EUR",
        "price": "13,50 €",
        "volume": "100ml",
        "variantLabel": "",
        "category": "hair",
        "kind": "Kondicionéry",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "balanced",
          "hydrate"
        ],
        "reason": "Z ponuky kondicionéry. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-2654038213.webp"
      },
      {
        "id": "catalogue-2421363013",
        "name": "Fresh air - prírodný deodorant",
        "url": "https://ponio.sk/products/fresh-air-prirodny-deodorant?variant=7007219909",
        "priceAmount": 9.3,
        "currency": "EUR",
        "price": "9,30 €",
        "volume": "50ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Dezodoranty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate"
        ],
        "reason": "Z ponuky dezodoranty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-2421363013.webp"
      },
      {
        "id": "catalogue-2411860933",
        "name": "Tea tree & lemongras - prírodný deodorant",
        "url": "https://ponio.sk/products/tea-tree-lemongras-prirodny-deodorant?variant=6979519813",
        "priceAmount": 9.3,
        "currency": "EUR",
        "price": "9,30 €",
        "volume": "50ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Dezodoranty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate"
        ],
        "reason": "Z ponuky dezodoranty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-2411860933.webp"
      },
      {
        "id": "catalogue-2256810373",
        "name": "Levanduľa & verbena - prírodné mydlo",
        "url": "https://ponio.sk/products/levandula-verbena-prirodne-mydlo?variant=6504161605",
        "priceAmount": 5.5,
        "currency": "EUR",
        "price": "5,50 €",
        "volume": "100g",
        "variantLabel": "",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-2256810373.webp"
      },
      {
        "id": "catalogue-451469988",
        "name": "Pomaranč & eukalyptus s rakytníkom",
        "url": "https://ponio.sk/products/pomaranc-a-eukalyptus-s-rakytnikom?variant=1264180156",
        "priceAmount": 5.5,
        "currency": "EUR",
        "price": "5,50 €",
        "volume": "100g",
        "variantLabel": "",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "sensitive",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-451469988.webp"
      },
      {
        "id": "catalogue-2421534725",
        "name": "Levanduľa & mäta - prírodný deodorant",
        "url": "https://ponio.sk/products/levandula-mata-prirodny-deodorant?variant=7007802565",
        "priceAmount": 9.3,
        "currency": "EUR",
        "price": "9,30 €",
        "volume": "50ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Dezodoranty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky dezodoranty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-2421534725.webp"
      },
      {
        "id": "catalogue-369375789",
        "name": "Tea tree & lemongras s rakytníkom",
        "url": "https://ponio.sk/products/cajovnik-a-lemongras-s-rakytnikom?variant=956064313",
        "priceAmount": 5.5,
        "currency": "EUR",
        "price": "5,50 €",
        "volume": "100g",
        "variantLabel": "",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "calm"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-369375789.webp"
      },
      {
        "id": "catalogue-211971309",
        "name": "Dvojitá levanduľa - žihľavový šampúch",
        "url": "https://ponio.sk/products/dvojita-levandula-zihlavovy-sampuch-30g-60g?variant=479979605",
        "priceAmount": 4.7,
        "currency": "EUR",
        "price": "4,70 €",
        "volume": "30 g",
        "variantLabel": "30 g",
        "category": "hair",
        "kind": "Šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "balanced",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-211971309.webp"
      },
      {
        "id": "catalogue-202545861",
        "name": "Citrón & rozmarín - žihľavový šampúch",
        "url": "https://ponio.sk/products/citron-a-rozmarin-zihlavovy-sampuch?variant=461719577",
        "priceAmount": 4.7,
        "currency": "EUR",
        "price": "4,70 €",
        "volume": "30 g",
        "variantLabel": "30 g",
        "category": "hair",
        "kind": "Šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "balanced",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-202545861.webp"
      },
      {
        "id": "catalogue-364021273",
        "name": "Rakytníkové jemné mydlo",
        "url": "https://ponio.sk/products/rakytnikove-jemne-mydlo?variant=931768621",
        "priceAmount": 3.9,
        "currency": "EUR",
        "price": "3,90 €",
        "volume": "100g",
        "variantLabel": "",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-364021273.webp"
      },
      {
        "id": "catalogue-269497621",
        "name": "Deodorant - náplň / rôzne druhy 50ml",
        "url": "https://ponio.sk/products/prirodny-dezodorant-napln?variant=30974867570803",
        "priceAmount": 7.7,
        "currency": "EUR",
        "price": "7,70 €",
        "volume": "50ml",
        "variantLabel": "Lavandin - bez sódy",
        "category": "body",
        "kind": "Dezodoranty",
        "tags": [
          "any",
          "basic",
          "full",
          "target"
        ],
        "reason": "Z ponuky dezodoranty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-269497621.webp"
      },
      {
        "id": "catalogue-328262145",
        "name": "Ichtamolové mydlo s rakytníkom",
        "url": "https://ponio.sk/products/ichtamolove-mydlo-s-rakytnikom?variant=790631357",
        "priceAmount": 5.5,
        "currency": "EUR",
        "price": "5,50 €",
        "volume": "100g",
        "variantLabel": "",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-328262145.webp"
      },
      {
        "id": "catalogue-203196273",
        "name": "Pofúkam ti boľačku... - masážna kocka",
        "url": "https://ponio.sk/products/pofukam-ti-bolacku?variant=463113437",
        "priceAmount": 5.9,
        "currency": "EUR",
        "price": "5,90 €",
        "volume": "37g",
        "variantLabel": "37g",
        "category": "body",
        "kind": "Telové krémy a maslá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "sensitive"
        ],
        "reason": "Z ponuky telové krémy a maslá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-203196273.webp"
      },
      {
        "id": "catalogue-206683497",
        "name": "Pánsky klub - prírodné mydlo",
        "url": "https://ponio.sk/products/pansky-klub-mydlo?variant=470405825",
        "priceAmount": 5.5,
        "currency": "EUR",
        "price": "5,50 €",
        "volume": "100g",
        "variantLabel": "",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-206683497.webp"
      },
      {
        "id": "catalogue-214984461",
        "name": "Aloe kapské - prírodné mydlo",
        "url": "https://ponio.sk/products/aloe-kapske-prirodne-mydlo?variant=484840029",
        "priceAmount": 5.5,
        "currency": "EUR",
        "price": "5,50 €",
        "volume": "100g",
        "variantLabel": "",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate",
          "calm",
          "mature"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-214984461.webp"
      },
      {
        "id": "catalogue-264114233",
        "name": "Dvojitá levanduľa bez kvetov - prírodné mydlo",
        "url": "https://ponio.sk/products/dvojita-levandula-bez-kvetov-prirodne-mydlo?variant=613106637",
        "priceAmount": 5.5,
        "currency": "EUR",
        "price": "5,50 €",
        "volume": "100g",
        "variantLabel": "",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive",
          "calm"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-264114233.webp"
      },
      {
        "id": "catalogue-202556753",
        "name": "Bambucké jemné mydlo",
        "url": "https://ponio.sk/products/bambucke-jemne-mydlo?variant=461741637",
        "priceAmount": 3.9,
        "currency": "EUR",
        "price": "3,90 €",
        "volume": "100g",
        "variantLabel": "",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-202556753.webp"
      },
      {
        "id": "catalogue-225467457",
        "name": "Olivové jemné mydlo",
        "url": "https://ponio.sk/products/olivove-jemne-mydlo?variant=505013721",
        "priceAmount": 3.7,
        "currency": "EUR",
        "price": "3,70 €",
        "volume": "100g",
        "variantLabel": "",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "sensitive",
          "hydrate"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-225467457.webp"
      },
      {
        "id": "catalogue-221782357",
        "name": "Dvojitá levanduľa - prírodné mydlo",
        "url": "https://ponio.sk/products/dvojita-levandula-prirodne-mydlo?variant=496546865",
        "priceAmount": 5.5,
        "currency": "EUR",
        "price": "5,50 €",
        "volume": "100g",
        "variantLabel": "",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive",
          "calm"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-221782357.webp"
      },
      {
        "id": "catalogue-206738633",
        "name": "Vanilková kocka",
        "url": "https://ponio.sk/products/vanilkova-kocka?variant=470489865",
        "priceAmount": 6.5,
        "currency": "EUR",
        "price": "6,50 €",
        "volume": "50g",
        "variantLabel": "50g",
        "category": "body",
        "kind": "Telové krémy a maslá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive",
          "calm"
        ],
        "reason": "Z ponuky telové krémy a maslá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-206738633.webp"
      },
      {
        "id": "catalogue-273446865",
        "name": "Pomaranč & eukalyptus - masážna kocka",
        "url": "https://ponio.sk/products/pomaranc-a-eukalyptus-masazna-kocka-50g-100g?variant=642169953",
        "priceAmount": 6.5,
        "currency": "EUR",
        "price": "6,50 €",
        "volume": "50g",
        "variantLabel": "50g",
        "category": "body",
        "kind": "Telové krémy a maslá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky telové krémy a maslá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-273446865.webp"
      },
      {
        "id": "catalogue-208394477",
        "name": "Dvojitá levanduľa - masážna kocka",
        "url": "https://ponio.sk/products/dvojita-levandula-masazna-kocka?variant=473657241",
        "priceAmount": 6.5,
        "currency": "EUR",
        "price": "6,50 €",
        "volume": "50g",
        "variantLabel": "50g",
        "category": "body",
        "kind": "Telové krémy a maslá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky telové krémy a maslá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-208394477.webp"
      },
      {
        "id": "catalogue-208431393",
        "name": "Kakao & mäta - masážna kocka",
        "url": "https://ponio.sk/products/kakao-a-mata-masazna-kocka?variant=473761505",
        "priceAmount": 6.5,
        "currency": "EUR",
        "price": "6,50 €",
        "volume": "50g",
        "variantLabel": "50g",
        "category": "body",
        "kind": "Telové krémy a maslá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "calm",
          "mature"
        ],
        "reason": "Z ponuky telové krémy a maslá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-208431393.webp"
      },
      {
        "id": "catalogue-271118093",
        "name": "Cukrová pivonka - masážna kocka",
        "url": "https://ponio.sk/products/cukrova-pivonka-masazna-kocka-50g-100g?variant=635802101",
        "priceAmount": 6.5,
        "currency": "EUR",
        "price": "6,50 €",
        "volume": "50g",
        "variantLabel": "50g",
        "category": "body",
        "kind": "Telové krémy a maslá",
        "tags": [
          "any",
          "basic",
          "full",
          "target"
        ],
        "reason": "Z ponuky telové krémy a maslá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-271118093.webp"
      },
      {
        "id": "catalogue-208406441",
        "name": "Kakaová kocka",
        "url": "https://ponio.sk/products/kakaova-kocka?variant=473691681",
        "priceAmount": 6.5,
        "currency": "EUR",
        "price": "6,50 €",
        "volume": "50g",
        "variantLabel": "50g",
        "category": "body",
        "kind": "Telové krémy a maslá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "calm"
        ],
        "reason": "Z ponuky telové krémy a maslá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-208406441.webp"
      },
      {
        "id": "catalogue-226017657",
        "name": "Šampúch s ichtamolom",
        "url": "https://ponio.sk/products/sampuch-s-ichtamolom-30g-60g?variant=506124009",
        "priceAmount": 5.0,
        "currency": "EUR",
        "price": "5,00 €",
        "volume": "30 g",
        "variantLabel": "30 g",
        "category": "hair",
        "kind": "Šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-226017657.webp"
      },
      {
        "id": "catalogue-273454157",
        "name": "Pomaranč & eukalyptus - žihľavový šampúch",
        "url": "https://ponio.sk/products/pomaranc-a-eukalyptus-zihlavovy-sampuch-30g-60g?variant=642200933",
        "priceAmount": 4.7,
        "currency": "EUR",
        "price": "4,70 €",
        "volume": "30 g",
        "variantLabel": "30 g",
        "category": "hair",
        "kind": "Šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "balanced",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-273454157.webp"
      },
      {
        "id": "catalogue-271129413",
        "name": "Cukrová pivonka - žihľavový šampúch",
        "url": "https://ponio.sk/products/cukrova-pivonka-zihlavovy-sampuch-30g-60g?variant=635827165",
        "priceAmount": 4.7,
        "currency": "EUR",
        "price": "4,70 €",
        "volume": "30 g",
        "variantLabel": "30 g",
        "category": "hair",
        "kind": "Šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "balanced",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/ponio-catalogue-271129413.webp"
      }
    ]
  },
  "bellcoria": {
    "verifiedAt": "2026-10-09T20:40:07.129505+00:00",
    "products": [
      {
        "id": "catalogue-10001",
        "name": "Organický opunciový olej",
        "url": "https://bellcoria.sk/produkty/organicky-opunciovy-olej/",
        "priceAmount": 30.9,
        "currency": "EUR",
        "price": "30,90 €",
        "volume": "30 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové oleje",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate",
          "mature",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky pleťové oleje. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-10001.webp"
      },
      {
        "id": "catalogue-6705",
        "name": "Telový olej na podporu opálenia s astaxantínom",
        "url": "https://bellcoria.sk/produkty/telovy-olej-na-podporu-opalenia-s-astaxantinom/",
        "priceAmount": 10.9,
        "currency": "EUR",
        "price": "10,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Telové oleje",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "sensitive",
          "hydrate",
          "mature"
        ],
        "reason": "Z ponuky telové oleje. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-6705.webp"
      },
      {
        "id": "catalogue-6675",
        "name": "Tuhý šampón na tmavé vlasy",
        "url": "https://bellcoria.sk/produkty/tuhy-sampon-na-tmave-vlasy/",
        "priceAmount": 6.9,
        "currency": "EUR",
        "price": "6,90 €",
        "volume": "40 g",
        "variantLabel": "",
        "category": "hair",
        "kind": "Šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily"
        ],
        "reason": "Z ponuky šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-6675.webp"
      },
      {
        "id": "catalogue-4528",
        "name": "Ružová záhrada – darčeková sada",
        "url": "https://bellcoria.sk/produkty/ruzova-zahrada-darcekova-sada/",
        "priceAmount": 30.9,
        "currency": "EUR",
        "price": "30,90 €",
        "volume": "celá sada",
        "variantLabel": "",
        "category": "sets",
        "kind": "Sady",
        "tags": [
          "any",
          "basic",
          "full",
          "target"
        ],
        "reason": "Z ponuky sady. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-4528.webp"
      },
      {
        "id": "catalogue-3031",
        "name": "Mami – darčeková sada",
        "url": "https://bellcoria.sk/produkty/mami-darcekova-sada/",
        "priceAmount": 62.9,
        "currency": "EUR",
        "price": "62,90 €",
        "volume": "celá sada",
        "variantLabel": "",
        "category": "sets",
        "kind": "Sady",
        "tags": [
          "any",
          "basic",
          "full",
          "target"
        ],
        "reason": "Z ponuky sady. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-3031.webp"
      },
      {
        "id": "catalogue-2696",
        "name": "Elixír proti vráskam s bakuchiolom",
        "url": "https://bellcoria.sk/produkty/elixir-proti-vraskam-s-bakuchiolom/",
        "priceAmount": 27.9,
        "currency": "EUR",
        "price": "27,90 €",
        "volume": "30 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové séra",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "sensitive",
          "calm",
          "mature",
          "serum"
        ],
        "reason": "Z ponuky pleťové séra. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-2696.webp"
      },
      {
        "id": "catalogue-2388",
        "name": "Pokoj – darčeková sada",
        "url": "https://bellcoria.sk/produkty/pokoj-darcekova-sada/",
        "priceAmount": 30.9,
        "currency": "EUR",
        "price": "30,90 €",
        "volume": "celá sada",
        "variantLabel": "",
        "category": "sets",
        "kind": "Sady",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "calm"
        ],
        "reason": "Z ponuky sady. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-2388.webp"
      },
      {
        "id": "catalogue-2390",
        "name": "Energia – darčeková sada",
        "url": "https://bellcoria.sk/produkty/energia-darcekova-sada-prirodnej-kozmetiky/",
        "priceAmount": 30.9,
        "currency": "EUR",
        "price": "30,90 €",
        "volume": "celá sada",
        "variantLabel": "",
        "category": "sets",
        "kind": "Sady",
        "tags": [
          "any",
          "basic",
          "full",
          "target"
        ],
        "reason": "Z ponuky sady. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-2390.webp"
      },
      {
        "id": "catalogue-2354",
        "name": "Slivkový olej",
        "url": "https://bellcoria.sk/produkty/slivkovy-olej/",
        "priceAmount": 13.9,
        "currency": "EUR",
        "price": "13,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové oleje",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "mature",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky pleťové oleje. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-2354.webp"
      },
      {
        "id": "catalogue-2304",
        "name": "Prémiové prírodné mydlo Energia",
        "url": "https://bellcoria.sk/produkty/premiove-prirodne-mydlo-energia/",
        "priceAmount": 6.9,
        "currency": "EUR",
        "price": "6,90 €",
        "volume": "90 g",
        "variantLabel": "",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-2304.webp"
      },
      {
        "id": "catalogue-2299",
        "name": "Prémiové prírodné mydlo Pokoj",
        "url": "https://bellcoria.sk/produkty/premiove-prirodne-mydlo-pokoj/",
        "priceAmount": 6.9,
        "currency": "EUR",
        "price": "6,90 €",
        "volume": "90 g",
        "variantLabel": "",
        "category": "body",
        "kind": "Mydlá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive",
          "calm"
        ],
        "reason": "Z ponuky mydlá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-2299.webp"
      },
      {
        "id": "catalogue-2123",
        "name": "Pleťový čistiaci gél",
        "url": "https://bellcoria.sk/produkty/pletovy-cistiaci-gel/",
        "priceAmount": 9.9,
        "currency": "EUR",
        "price": "9,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Čistenie a odličovanie",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "sensitive",
          "calm"
        ],
        "reason": "Z ponuky čistenie a odličovanie. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-2123.webp"
      },
      {
        "id": "catalogue-2116",
        "name": "Regeneračný elixír na nechty",
        "url": "https://bellcoria.sk/produkty/regeneracny-elixir-na-nechty/",
        "priceAmount": 5.9,
        "currency": "EUR",
        "price": "5,90 €",
        "volume": "10 ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Nechty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "serum"
        ],
        "reason": "Z ponuky nechty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-2116.webp"
      },
      {
        "id": "catalogue-1978",
        "name": "Nechtíkový balzam",
        "url": "https://bellcoria.sk/produkty/nechtikovy-balzam/",
        "priceAmount": 9.9,
        "currency": "EUR",
        "price": "9,90 €",
        "volume": "60 ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Nechty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive",
          "cream",
          "simple"
        ],
        "reason": "Z ponuky nechty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-1978.webp"
      },
      {
        "id": "catalogue-1968",
        "name": "Nočný elixír proti vráskam so stabilizovaným vitamínom C a brusnicovým olejom",
        "url": "https://bellcoria.sk/produkty/nocny-elixir-proti-vraskam-so-stabilizovanym-vitaminom-c-a-brusnicovym-olejom/",
        "priceAmount": 27.9,
        "currency": "EUR",
        "price": "27,90 €",
        "volume": "30 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové séra",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "hydrate",
          "mature",
          "serum"
        ],
        "reason": "Z ponuky pleťové séra. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-1968.webp"
      },
      {
        "id": "catalogue-1967",
        "name": "Krémový dezodorant Ruža",
        "url": "https://bellcoria.sk/produkty/kremovy-dezodorant-damasska-ruza/",
        "priceAmount": 8.9,
        "currency": "EUR",
        "price": "8,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Dezodoranty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "sensitive"
        ],
        "reason": "Z ponuky dezodoranty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-1967.webp"
      },
      {
        "id": "catalogue-1966",
        "name": "Tuhý šampón ",
        "url": "https://bellcoria.sk/produkty/tuhy-sampon-na-rast-vlasov/",
        "priceAmount": 6.9,
        "currency": "EUR",
        "price": "6,90 €",
        "volume": "40 g",
        "variantLabel": "",
        "category": "hair",
        "kind": "Šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate"
        ],
        "reason": "Z ponuky šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-1966.webp"
      },
      {
        "id": "catalogue-1516",
        "name": "Makadamiový olej",
        "url": "https://bellcoria.sk/produkty/makadamiovy-olej/",
        "priceAmount": 7.9,
        "currency": "EUR",
        "price": "7,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové oleje",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky pleťové oleje. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-1516.webp"
      },
      {
        "id": "catalogue-1299",
        "name": "Prírodný ANTI-AGING komplex — sada",
        "url": "https://bellcoria.sk/produkty/prirodny-anti-aging-komplex/",
        "priceAmount": 40.9,
        "currency": "EUR",
        "price": "40,90 €",
        "volume": "celá sada",
        "variantLabel": "2 × 30 ml",
        "category": "sets",
        "kind": "Sady",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "sensitive",
          "hydrate",
          "calm",
          "mature",
          "cream",
          "simple"
        ],
        "reason": "Z ponuky sady. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-1299.webp"
      },
      {
        "id": "catalogue-1195",
        "name": "Francúzsky ružový íl",
        "url": "https://bellcoria.sk/produkty/francuzsky-ruzovy-il/",
        "priceAmount": 7.9,
        "currency": "EUR",
        "price": "7,90 €",
        "volume": "120 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové masky",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive",
          "calm",
          "mature",
          "mask"
        ],
        "reason": "Z ponuky pleťové masky. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-1195.webp"
      },
      {
        "id": "catalogue-1194",
        "name": "Francúzsky zelený íl",
        "url": "https://bellcoria.sk/produkty/francuzsky-zeleny-il/",
        "priceAmount": 5.9,
        "currency": "EUR",
        "price": "5,90 €",
        "volume": "120 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové masky",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "sensitive",
          "mask"
        ],
        "reason": "Z ponuky pleťové masky. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-1194.webp"
      },
      {
        "id": "catalogue-1192",
        "name": "Marocký červený íl",
        "url": "https://bellcoria.sk/produkty/marocky-cerveny-il/",
        "priceAmount": 7.9,
        "currency": "EUR",
        "price": "7,90 €",
        "volume": "120 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové masky",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate",
          "mask"
        ],
        "reason": "Z ponuky pleťové masky. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-1192.webp"
      },
      {
        "id": "catalogue-1087",
        "name": "Tuhý žihľavový šampón proti lupinám",
        "url": "https://bellcoria.sk/produkty/tuhy-zihlavovy-sampon-proti-lupinam/",
        "priceAmount": 6.9,
        "currency": "EUR",
        "price": "6,90 €",
        "volume": "40 g",
        "variantLabel": "",
        "category": "hair",
        "kind": "Šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate"
        ],
        "reason": "Z ponuky šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-1087.webp"
      },
      {
        "id": "catalogue-1082",
        "name": "Tuhý šampón pre lesk vlasov",
        "url": "https://bellcoria.sk/produkty/tuhy-sampon-pre-lesk-vlasov/",
        "priceAmount": 6.9,
        "currency": "EUR",
        "price": "6,90 €",
        "volume": "40 g",
        "variantLabel": "",
        "category": "hair",
        "kind": "Šampóny",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky šampóny. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-1082.webp"
      },
      {
        "id": "catalogue-926",
        "name": "Sérum proti vráskam s kyselinou hyalurónovou",
        "url": "https://bellcoria.sk/produkty/serum-proti-vraskam-s-kyselinou-hyaluronovou/",
        "priceAmount": 27.9,
        "currency": "EUR",
        "price": "27,90 €",
        "volume": "30 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové séra",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate",
          "mature",
          "serum"
        ],
        "reason": "Z ponuky pleťové séra. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-926.webp"
      },
      {
        "id": "catalogue-694",
        "name": "Krémový dezodorant Citrus",
        "url": "https://bellcoria.sk/produkty/kremovy-dezodorant-citrus/",
        "priceAmount": 8.9,
        "currency": "EUR",
        "price": "8,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Dezodoranty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "sensitive",
          "hydrate"
        ],
        "reason": "Z ponuky dezodoranty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-694.webp"
      },
      {
        "id": "catalogue-691",
        "name": "Krémový dezodorant Bylinky",
        "url": "https://bellcoria.sk/produkty/kremovy-dezodorant-ruza-a-bylinky/",
        "priceAmount": 8.9,
        "currency": "EUR",
        "price": "8,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Dezodoranty",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "sensitive",
          "hydrate"
        ],
        "reason": "Z ponuky dezodoranty. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-691.webp"
      },
      {
        "id": "catalogue-523",
        "name": "Čajovníková kvetová voda",
        "url": "https://bellcoria.sk/produkty/cajovnikova-kvetova-voda/",
        "priceAmount": 5.9,
        "currency": "EUR",
        "price": "5,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové vody a tonery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily"
        ],
        "reason": "Z ponuky pleťové vody a tonery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-523.webp"
      },
      {
        "id": "catalogue-501",
        "name": "Elixír na aknóznu a mastnú pleť",
        "url": "https://bellcoria.sk/produkty/elixir-na-aknoznu-a-mastnu-plet/",
        "priceAmount": 13.9,
        "currency": "EUR",
        "price": "13,90 €",
        "volume": "30 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové séra",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "sensitive",
          "hydrate",
          "calm",
          "mature",
          "serum"
        ],
        "reason": "Z ponuky pleťové séra. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-501.webp"
      },
      {
        "id": "catalogue-495",
        "name": "Elixír proti vráskam s koenzýmom Q10",
        "url": "https://bellcoria.sk/produkty/elixir-proti-vraskam-s-koenzymom-q10/",
        "priceAmount": 20.9,
        "currency": "EUR",
        "price": "20,90 €",
        "volume": "30 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové séra",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "sensitive",
          "hydrate",
          "calm",
          "mature",
          "serum"
        ],
        "reason": "Z ponuky pleťové séra. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-495.webp"
      },
      {
        "id": "catalogue-345",
        "name": "Pomarančový penový krém",
        "url": "https://bellcoria.sk/produkty/pomarancovy-penovy-krem/",
        "priceAmount": 11.9,
        "currency": "EUR",
        "price": "11,90 €",
        "volume": "120 ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Telové krémy a maslá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate"
        ],
        "reason": "Z ponuky telové krémy a maslá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-345.webp"
      },
      {
        "id": "catalogue-344",
        "name": "Ružový penový krém",
        "url": "https://bellcoria.sk/produkty/ruzovy-penovy-krem/",
        "priceAmount": 11.9,
        "currency": "EUR",
        "price": "11,90 €",
        "volume": "120 ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Telové krémy a maslá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate",
          "mature"
        ],
        "reason": "Z ponuky telové krémy a maslá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-344.webp"
      },
      {
        "id": "catalogue-343",
        "name": "Levanduľový penový krém",
        "url": "https://bellcoria.sk/produkty/levandulovy-penovy-krem/",
        "priceAmount": 11.9,
        "currency": "EUR",
        "price": "11,90 €",
        "volume": "120 ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Telové krémy a maslá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky telové krémy a maslá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-343.webp"
      },
      {
        "id": "catalogue-342",
        "name": "Marhuľový penový krém",
        "url": "https://bellcoria.sk/produkty/marhulovy-penovy-krem/",
        "priceAmount": 11.9,
        "currency": "EUR",
        "price": "11,90 €",
        "volume": "120 ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Telové krémy a maslá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky telové krémy a maslá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-342.webp"
      },
      {
        "id": "catalogue-334",
        "name": "Jazmínová kvetová voda",
        "url": "https://bellcoria.sk/produkty/jazminova-kvetova-voda/",
        "priceAmount": 7.9,
        "currency": "EUR",
        "price": "7,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové vody a tonery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "hydrate"
        ],
        "reason": "Z ponuky pleťové vody a tonery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-334.webp"
      },
      {
        "id": "catalogue-333",
        "name": "Rozmarínová kvetová voda",
        "url": "https://bellcoria.sk/produkty/rozmarinova-kvetova-voda/",
        "priceAmount": 5.9,
        "currency": "EUR",
        "price": "5,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové vody a tonery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky pleťové vody a tonery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-333.webp"
      },
      {
        "id": "catalogue-328",
        "name": "Rumančeková kvetová voda",
        "url": "https://bellcoria.sk/produkty/rumancekova-kvetova-voda/",
        "priceAmount": 5.9,
        "currency": "EUR",
        "price": "5,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové vody a tonery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "sensitive",
          "hydrate"
        ],
        "reason": "Z ponuky pleťové vody a tonery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-328.webp"
      },
      {
        "id": "catalogue-326",
        "name": "Mätová kvetová voda",
        "url": "https://bellcoria.sk/produkty/matova-kvetova-voda/",
        "priceAmount": 5.9,
        "currency": "EUR",
        "price": "5,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové vody a tonery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate",
          "calm"
        ],
        "reason": "Z ponuky pleťové vody a tonery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-326.webp"
      },
      {
        "id": "catalogue-324",
        "name": "Ružová kvetová voda",
        "url": "https://bellcoria.sk/produkty/ruzova-kvetova-voda/",
        "priceAmount": 5.9,
        "currency": "EUR",
        "price": "5,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové vody a tonery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "sensitive",
          "hydrate",
          "calm",
          "mature"
        ],
        "reason": "Z ponuky pleťové vody a tonery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-324.webp"
      },
      {
        "id": "catalogue-323",
        "name": "Levanduľová kvetová voda",
        "url": "https://bellcoria.sk/produkty/levandulova-kvetova-voda/",
        "priceAmount": 5.9,
        "currency": "EUR",
        "price": "5,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové vody a tonery",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "sensitive",
          "hydrate"
        ],
        "reason": "Z ponuky pleťové vody a tonery. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-323.webp"
      },
      {
        "id": "catalogue-322",
        "name": "Kokosový penový krém",
        "url": "https://bellcoria.sk/produkty/kokosovy-penovy-krem/",
        "priceAmount": 11.9,
        "currency": "EUR",
        "price": "11,90 €",
        "volume": "120 ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Telové krémy a maslá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "hydrate"
        ],
        "reason": "Z ponuky telové krémy a maslá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-322.webp"
      },
      {
        "id": "catalogue-320",
        "name": "Bambucké maslo",
        "url": "https://bellcoria.sk/produkty/bambucke-maslo/",
        "priceAmount": 11.9,
        "currency": "EUR",
        "price": "11,90 €",
        "volume": "120 ml",
        "variantLabel": "",
        "category": "body",
        "kind": "Telové krémy a maslá",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oily",
          "mature"
        ],
        "reason": "Z ponuky telové krémy a maslá. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-320.webp"
      },
      {
        "id": "catalogue-318",
        "name": "Marhuľový olej",
        "url": "https://bellcoria.sk/produkty/marhulovy-olej/",
        "priceAmount": 7.9,
        "currency": "EUR",
        "price": "7,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové oleje",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky pleťové oleje. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-318.webp"
      },
      {
        "id": "catalogue-317",
        "name": "Mandľový olej",
        "url": "https://bellcoria.sk/produkty/mandlovy-olej/",
        "priceAmount": 7.9,
        "currency": "EUR",
        "price": "7,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové oleje",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky pleťové oleje. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-317.webp"
      },
      {
        "id": "catalogue-316",
        "name": "Jojobový olej",
        "url": "https://bellcoria.sk/produkty/jojobovy-olej/",
        "priceAmount": 7.9,
        "currency": "EUR",
        "price": "7,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové oleje",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "hydrate",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky pleťové oleje. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-316.webp"
      },
      {
        "id": "catalogue-315",
        "name": "Ovsený olej",
        "url": "https://bellcoria.sk/produkty/ovseny-olej/",
        "priceAmount": 18.9,
        "currency": "EUR",
        "price": "18,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové oleje",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "sensitive",
          "hydrate",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky pleťové oleje. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-315.webp"
      },
      {
        "id": "catalogue-314",
        "name": "Hroznový olej",
        "url": "https://bellcoria.sk/produkty/hroznovy-olej/",
        "priceAmount": 5.9,
        "currency": "EUR",
        "price": "5,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové oleje",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "oily",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky pleťové oleje. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-314.webp"
      },
      {
        "id": "catalogue-313",
        "name": "Argánový olej",
        "url": "https://bellcoria.sk/produkty/arganovy-olej/",
        "priceAmount": 11.9,
        "currency": "EUR",
        "price": "11,90 €",
        "volume": "50 ml",
        "variantLabel": "",
        "category": "face",
        "kind": "Pleťové oleje",
        "tags": [
          "any",
          "basic",
          "full",
          "target",
          "dry",
          "mature",
          "oil",
          "simple"
        ],
        "reason": "Z ponuky pleťové oleje. Presné balenie a cenu potvrdíte v e-shope.",
        "photo": "/assets/catalogue/bellcoria-catalogue-313.webp"
      }
    ]
  }
};
