(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const svg=(body,v='0 0 24 24')=>`<svg viewBox="${v}" fill="none" aria-hidden="true">${body}</svg>`;
  const p=(d,e='')=>`<path d="${d}" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" ${e}/>`;
  const icons={
    refresh:svg(p('M20 11a8 8 0 1 0-2.3 5.7')+p('M20 5v6h-6')),close:svg(p('m6 6 12 12M18 6 6 18')),back:svg(p('m15 18-6-6 6-6')),next:svg(p('m9 18 6-6-6-6')),send:svg(p('m4 4 16 8-16 8 3-8-3-8Z')+p('M7 12h13')),check:svg(p('m5 12 4 4L19 6')),
    chat:svg(p('M5 18.5 3.5 21v-5A8.5 8.5 0 1 1 12 20.5c-2.7 0-5.1-.7-7-2Z')+p('M8 12h.01M12 12h.01M16 12h.01')),
    spark:svg(p('M12 3l1.5 5.5L19 10l-5.5 1.5L12 17l-1.5-5.5L5 10l5.5-1.5L12 3Z')+p('M19 16l.7 2.3L22 19l-2.3.7L19 22l-.7-2.3L16 19l2.3-.7L19 16Z')),
    machine:svg(`<rect x="4" y="3" width="16" height="15" rx="3" stroke="currentColor" stroke-width="1.9"/>`+p('M8 7h8M8 11h5v3H8zM7 21h10M17 10v5')),
    lever:svg(p('M5 20h14M7 20V9h10v11M9 9V5h6v4M15 12h4M19 12v5')+`<path d="M9 14h6v3H9z" stroke="currentColor" stroke-width="1.9"/>`),
    moka:svg(p('m8 3 8 1 2 6-2 11H8L6 10l2-7Z')+p('M7 10h10M9 5h6M18 8h2.5v6H18')),
    filter:svg(p('M6 4h12l-2 10H8L6 4Z')+p('M9 18h6M12 14v4M8 4l4 10 4-10')),
    gentle:svg(p('M4 14c4-1 4-7 8-8 4-1 4 5 8 4M5 18h14')),balanced:svg(p('M12 3v18M5 7h14M6 7l-3 7h6L6 7Zm12 0-3 7h6l-3-7Z')),strong:svg(p('M8 21c-2-4 1-6 2-9 1-2 0-5 2-9 4 4 5 7 4 10 3-1 4-2 4-4 3 6 0 12-6 12H8Z')),unsure:svg(`<circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="1.9"/>`+p('M9.8 9a2.3 2.3 0 1 1 3.7 1.8c-.9.6-1.5 1-1.5 2.2M12 17h.01')),
    black:svg(p('M5 8h12v7a5 5 0 0 1-5 5h-2a5 5 0 0 1-5-5V8ZM17 10h2a2 2 0 0 1 0 4h-2M8 4c0 1 1 1 1 2M12 4c0 1 1 1 1 2')),milk:svg(p('M7 3h10l1 4v14H6V7l1-4ZM6 8h12M9 12c2 2 4 2 6 0')),both:svg(`<path d="M4 6h7v12H4zM13 6h7v12h-7z" stroke="currentColor" stroke-width="1.9"/>`+p('M6 9h3M15 9h3M6 13h3M15 13h3')),
    classic:svg(p('m13 2-7 11h6l-1 9 7-12h-6l1-8Z')),decaf:svg(p('M20 15.5A8 8 0 1 1 8.5 4 7 7 0 0 0 20 15.5ZM15 5h.01M18 8h.01')),either:svg(p('M5 8h14M5 16h14M16 5l3 3-3 3M8 13l-3 3 3 3'))
  };
  $$('[data-icon]').forEach(el=>el.innerHTML=icons[el.dataset.icon]||'');

  const questions=[
    {key:'prep',name:'Príprava',title:'Ako kávu najčastejšie pripravujete?',help:'Vyberte zariadenie, ktoré používate najviac.',options:[['automatic','machine','Automatický kávovar','Stlačím tlačidlo a káva je hotová'],['lever','lever','Pákový kávovar','Espresso pripravujem ručne'],['moka','moka','Moka kanvička','Výrazná domáca káva na sporáku'],['filter','filter','Filter alebo zalievanie','V60, French press alebo klasické zalievanie']]},
    {key:'taste',name:'Chuť',title:'Aká chuť vám sedí najviac?',help:'Nemusíte poznať odborné názvy. Vyberte podľa pocitu.',options:[['gentle','gentle','Jemná a sladšia','Čokoláda, kakao, minimum horkosti'],['balanced','balanced','Vyvážená','Plná chuť bez extrémov'],['strong','strong','Silná a výrazná','Hustá kréma a intenzívnejší dojem'],['unsure','unsure','Neviem to pomenovať','Bezpečná univerzálna voľba']]},
    {key:'drink',name:'Nápoj',title:'Ako kávu pijete najčastejšie?',help:'Mlieko mení intenzitu aj vnímanie chuti.',options:[['black','black','Čiernu','Espresso, lungo alebo filtrovanú'],['milk','milk','S mliekom','Cappuccino, flat white alebo latte'],['both','both','Striedam oboje','Potrebujem univerzálnu kávu']]},
    {key:'caffeine',name:'Kofeín',title:'Klasickú alebo bezkofeínovú?',help:'Posledná odpoveď a pripravíme odporúčanie.',options:[['classic','classic','Klasickú','Bežná káva s kofeínom'],['decaf','decaf','Bezkofeínovú','Na večer alebo bez povzbudenia'],['either','either','Je mi to jedno','Rozhodnite najmä podľa chuti']]}
  ];

  const products=[
    {id:'paganini',name:'Paganini blend',short:'PAGANINI',origin:'75 % Arabica · 25 % Robusta',price:{250:11.9,500:18.9,1000:33.9},prep:['automatic','lever','moka'],taste:['balanced','unsure'],drink:['milk','black','both'],caffeine:['classic','either'],tags:['čokoláda','mandle','krémová'],reason:'Vyvážená zmes s plným telom, ktorá funguje ako espresso aj v mliečnych nápojoch.',metrics:{sweet:7,bitter:4,acid:2,crema:8},pack:'paganini'},
    {id:'brazil',name:'Brazil Santos',short:'BRAZIL',origin:'100 % Arabica',price:{250:9.9,500:15.5,1000:27},prep:['automatic','lever','moka','filter'],taste:['gentle','unsure'],drink:['black','both'],caffeine:['classic','either'],tags:['čokoláda','kakao','nízka acidita'],reason:'Sladšia arabica s minimálnou horkosťou a aciditou. Veľmi bezpečná voľba na každý deň.',metrics:{sweet:8,bitter:3,acid:2,crema:7},pack:'brazil'},
    {id:'puccini',name:'Puccini blend',short:'PUCCINI',origin:'60 % Arabica · 40 % Robusta',price:{250:11.5,500:18,1000:31},prep:['automatic','lever','moka'],taste:['strong','balanced'],drink:['milk','both'],caffeine:['classic','either'],tags:['tmavá čokoláda','silná','hustá kréma'],reason:'Výraznejšia zmes s vysokou krémou, ktorá sa nestratí ani v cappuccine alebo latte.',metrics:{sweet:8,bitter:4,acid:1,crema:9},pack:'puccini'},
    {id:'cuba',name:'Cuba Serrano Lavado',short:'CUBA',origin:'100 % Arabica',price:{250:12.9,500:19.5,1000:34},prep:['lever','moka','filter'],taste:['gentle','balanced'],drink:['black'],caffeine:['classic','either'],tags:['kakao','vlašské orechy','nulová acidita'],reason:'Plná a sladká arabica s kakaovým telom a prakticky nulovou aciditou.',metrics:{sweet:9,bitter:4,acid:0,crema:9},pack:'cuba'},
    {id:'decaf',name:'Bezkofeínová Brazil',short:'DECAF',origin:'100 % Arabica · bez kofeínu',price:{250:12.9,500:19.5,1000:34},prep:['automatic','lever','moka','filter'],taste:['gentle','balanced','unsure'],drink:['black','milk','both'],caffeine:['decaf'],tags:['bez kofeínu','jemná','na večer'],reason:'Kávový zážitok bez povzbudivého účinku. Vhodná večer aj pre citlivejších zákazníkov.',metrics:{sweet:4,bitter:6,acid:1,crema:3},pack:'decaf'}
  ];

  const state={mode:'chat',step:0,answers:{},selectedProduct:null,weight:null,grind:'beans',stage:'questions'};
  const widget=$('#widget'),launcher=$('#launcher'),modeSwitch=$('#modeSwitch'),chatScreen=$('#chatScreen'),advisorScreen=$('#advisorScreen'),chat=$('#chatMessages'),chips=$('#quickChips'),advisor=$('#advisorBody'),prev=$('#prevBtn'),next=$('#nextBtn'),footerStatus=$('#footerStatus'),savedProgress=$('#savedProgress');
  const money=n=>`${n.toFixed(2).replace('.',',')} €`, time=()=>new Date().toLocaleTimeString('sk-SK',{hour:'2-digit',minute:'2-digit'}),scrollBottom=el=>requestAnimationFrame(()=>el.scrollTop=el.scrollHeight);
  const avatar=()=>`<span class="message__avatar"><img src="brand/praziarnicka-mark.svg" alt=""></span>`;
  function openWidget(){widget.classList.add('is-open');widget.setAttribute('aria-hidden','false');launcher.style.display='none';document.documentElement.classList.add('widget-open');document.body.classList.add('widget-open')}
  function closeWidget(){widget.classList.remove('is-open');widget.setAttribute('aria-hidden','true');launcher.style.display='flex';document.documentElement.classList.remove('widget-open');document.body.classList.remove('widget-open')}
  function setMode(mode){state.mode=mode;modeSwitch.classList.toggle('is-advisor',mode==='advisor');$$('.mode__button').forEach(b=>b.classList.toggle('is-active',b.dataset.mode===mode));chatScreen.classList.toggle('is-active',mode==='chat');advisorScreen.classList.toggle('is-active',mode==='advisor');chatScreen.classList.toggle('is-left',mode==='advisor');if(mode==='advisor')renderAdvisor();else setTimeout(()=>$('#chatInput')?.focus(),120)}
  function updateSaved(){const n=Object.keys(state.answers).length;savedProgress.textContent=n;savedProgress.classList.toggle('is-visible',n>0&&state.stage==='questions')}
  function addMessage(text,user=false){const row=document.createElement('div');row.className=`message${user?' message--user':''}`;row.innerHTML=`${user?'':avatar()}<div class="message__stack"><div class="bubble">${text}</div><div class="timestamp">${time()}</div></div>`;chat.appendChild(row);scrollBottom(chat)}
  function typing(){const row=document.createElement('div');row.id='typingRow';row.className='message';row.innerHTML=`${avatar()}<div class="message__stack"><div class="bubble typing"><i></i><i></i><i></i></div></div>`;chat.appendChild(row);scrollBottom(chat)}
  const quick=['Káva do automatu','Nechcem kyslú kávu','Káva na cappuccino','Bezkofeínová'];
  function renderChips(){chips.innerHTML=quick.map(x=>`<button class="chip" type="button"><span>${x}</span></button>`).join('');$$('.chip',chips).forEach(b=>b.onclick=()=>sendChat(b.textContent.trim()))}
  function answer(t){t=t.toLowerCase();if(t.includes('automat'))return 'Do automatu odporúčame <b>Paganini</b>: stabilná kréma, vyvážená chuť a dobrý výsledok čierny aj s mliekom.';if(t.includes('kysl'))return '<b>Brazil Santos</b> má nízku aciditu a jemnú čokoládovú chuť. Ešte sladšia a bez acidity je Cuba Serrano.';if(t.includes('capp')||t.includes('mlie'))return '<b>Puccini</b> má plné telo a vysokú krému, preto sa v cappuccine nestratí. Jemnejšia alternatíva je Paganini.';if(t.includes('bez')||t.includes('večer'))return 'Bezkofeínová Brazil je vhodná večer a pripravíte ju v automate, páke, moka kanvičke aj filtri.';if(t.includes('mlet'))return 'Zrnková káva drží arómu najdlhšie. Pri mletej vyberte jemné mletie na espresso, stredné na moka a hrubšie na filter.';return 'Najpresnejší tip získate vo <b>Výbere kávy</b>. Zohľadní prípravu, chuť, mlieko aj kofeín.'}
  function sendChat(text){const v=text.trim();if(!v)return;addMessage(v,true);$('#chatInput').value='';typing();setTimeout(()=>{$('#typingRow')?.remove();addMessage(answer(v))},430)}
  function productScore(product){let s=0;for(const [k,v] of Object.entries(state.answers))if(product[k]?.includes(v))s+=k==='caffeine'?4:3;return s}
  function rankings(){return [...products].map(p=>({...p,score:productScore(p)})).sort((a,b)=>b.score-a.score)}
  function matchPercent(p){const list=rankings(),best=list[0];return Math.max(76,Math.min(98,88+(p.score-best.score)*4+(p.id===best.id?6:0)))}
  function pack(p,size=''){return `<div class="pack pack--${p.pack} ${size}"><span class="pack__brand">PRAŽIARNIČKA</span><strong>${p.short}</strong><small>${p.origin.toUpperCase()}</small><i></i></div>`}
  function progress(){const stageIndex=state.stage==='questions'?state.step:4;$('#stepLabel').textContent=state.stage==='questions'?`Krok ${state.step+1} zo 4`:state.stage==='result'?'Odporúčanie':'Dokončenie objednávky';$('#stepName').textContent=state.stage==='questions'?questions[state.step].name:state.stage==='result'?'Vaša káva':'Balenie a mletie';$('#progress').innerHTML=[0,1,2,3].map(i=>`<i class="${i<stageIndex?'is-done ':''}${i<=stageIndex?'is-active':''}"></i>`).join('')}
  function optionIcon(name){return icons[name]||icons.spark}
  function renderQuestions(){const q=questions[state.step],selected=state.answers[q.key];advisor.innerHTML=`<div class="question"><span class="question__kicker">${q.name}</span><h2>${q.title}</h2><p>${q.help}</p></div><div class="options">${q.options.map((o,i)=>`<button class="option ${selected===o[0]?'is-selected':selected?'is-muted':''}" type="button" data-value="${o[0]}" style="animation-delay:${i*40}ms"><span class="option__icon">${optionIcon(o[1])}</span><span class="option__copy"><b>${o[2]}</b><small>${o[3]}</small></span><span class="option__state">${selected===o[0]?icons.check:icons.next}</span></button>`).join('')}</div>${selected?`<div class="selection-note"><i>${icons.check}</i> Voľba je uložená. Môžete pokračovať.</div>`:''}`;
    $$('.option',advisor).forEach(btn=>btn.addEventListener('pointerdown',e=>{const r=btn.getBoundingClientRect();btn.style.setProperty('--fill-x',`${e.clientX-r.left}px`);btn.style.setProperty('--fill-y',`${e.clientY-r.top}px`)}));
    $$('.option',advisor).forEach(btn=>btn.onclick=()=>{state.answers[q.key]=btn.dataset.value;updateSaved();renderAdvisor()});prev.disabled=state.step===0;next.disabled=!selected;next.textContent=state.step===3?'Zobraziť odporúčanie':'Pokračovať ';next.insertAdjacentHTML('beforeend',icons.next);footerStatus.textContent=selected?'Voľba uložená':'Vyberte jednu možnosť';$('#advisorFooter').style.display='grid'}
  function metrics(p){const labels=[['Sladkosť','sweet'],['Horkosť','bitter'],['Acidita','acid'],['Kréma','crema']];return labels.map(([l,k])=>`<div class="metric"><div class="metric__top"><span>${l}</span><b>${p.metrics[k]}/10</b></div><div class="metric__bar"><i style="width:${p.metrics[k]*10}%"></i></div></div>`).join('')}
  function renderResult(){const list=rankings(),best=list[0];state.selectedProduct=state.selectedProduct||best.id;const p=list.find(x=>x.id===state.selectedProduct)||best,alternatives=list.filter(x=>x.id!==p.id).slice(0,2),percent=matchPercent(p);advisor.innerHTML=`<div class="result-head"><span class="result-head__badge">Najlepšia zhoda</span><h2>Táto káva vám sedí najviac</h2><p>Odporúčanie vzniklo z vašich štyroch odpovedí.</p></div><section class="result-card"><div class="result-card__top"><div class="match"><span class="match__ring" style="--score:${percent}"><b>${percent}%</b></span><span><b>Zhoda s preferenciami</b><small>${p.id===best.id?'Najsilnejšie odporúčanie':'Alternatívna voľba'}</small></span></div><span>Na sklade</span></div><div class="result-product">${pack(p)}<div><h3>${p.name}</h3><span class="result-product__origin">${p.origin}</span><div class="taste-tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></div></div><div class="reason"><b>Prečo práve táto</b><p>${p.reason}</p></div><div class="metrics">${metrics(p)}</div><div class="result-actions"><button class="result-button result-button--primary" id="choosePack">Vybrať balenie</button><button class="result-button result-button--secondary" id="restartResult">Upraviť odpovede</button></div><div class="alternatives"><span>Dobré alternatívy</span><div class="alternative-grid">${alternatives.map(a=>`<button class="alternative" data-id="${a.id}"><b>${a.name}</b><small>${a.tags.slice(0,2).join(' · ')}</small><em>${matchPercent(a)} % zhoda</em></button>`).join('')}</div></div></section>`;$('#choosePack').onclick=()=>{state.stage='package';state.weight=null;renderAdvisor()};$('#restartResult').onclick=()=>{state.stage='questions';state.step=0;renderAdvisor()};$$('.alternative',advisor).forEach(b=>b.onclick=()=>{state.selectedProduct=b.dataset.id;renderAdvisor()});$('#advisorFooter').style.display='none'}
  const grindOptions=[['beans','Zrnková','najviac arómy'],['espresso','Espresso','jemné mletie'],['moka','Moka','stredné mletie'],['filter','Filter','hrubšie mletie']];
  function renderPackage(){const p=products.find(x=>x.id===state.selectedProduct)||rankings()[0];advisor.innerHTML=`<div class="choice-head"><h2>Vyberte balenie</h2><p>Potom už iba zvoľte, či kávu chcete zrnkovú alebo zomletú.</p></div><div class="weight-grid">${[250,500,1000].map((w,i)=>`<button class="weight ${state.weight===w?'is-selected':''}" data-weight="${w}"><span class="weight__bag"></span><b>${w===1000?'1 kg':w+' g'}</b><small>${i===0?'na ochutnanie':i===1?'najčastejšia voľba':'najvýhodnejšie'}</small><strong>${money(p.price[w])}</strong></button>`).join('')}</div><div class="choice-section"><span>Ako ju pripraviť?</span><div class="grind-grid">${grindOptions.map(g=>`<button class="grind ${state.grind===g[0]?'is-selected':''}" data-grind="${g[0]}"><i>${g[0]==='beans'?'●':'≈'}</i><span><b>${g[1]}</b></span></button>`).join('')}</div></div><div class="summary"><div class="summary__row"><span>Káva</span><b>${p.name}</b></div><div class="summary__row"><span>Balenie</span><b>${state.weight?state.weight===1000?'1 kg':state.weight+' g':'—'}</b></div><div class="summary__row"><span>Úprava</span><b>${grindOptions.find(g=>g[0]===state.grind)[1]}</b></div><div class="summary__row summary__row--total"><span>Spolu</span><strong>${state.weight?money(p.price[state.weight]):'—'}</strong></div></div><button class="checkout-button" id="checkout" ${state.weight?'':'disabled'}>Pridať do košíka</button>`;$$('.weight',advisor).forEach(b=>b.onclick=()=>{state.weight=Number(b.dataset.weight);renderAdvisor()});$$('.grind',advisor).forEach(b=>b.onclick=()=>{state.grind=b.dataset.grind;renderAdvisor()});$('#checkout').onclick=()=>{state.stage='success';renderAdvisor()};$('#advisorFooter').style.display='none'}
  function renderSuccess(){const p=products.find(x=>x.id===state.selectedProduct);advisor.innerHTML=`<div class="success"><div class="success__icon">${icons.check}</div><h2>Káva je pripravená</h2><p>${p.name}, ${state.weight===1000?'1 kg':state.weight+' g'}, ${grindOptions.find(g=>g[0]===state.grind)[1].toLowerCase()}. V reálnom e-shope by sa teraz vložila do košíka.</p><button class="result-button result-button--primary" id="startAgain">Vybrať ďalšiu kávu</button></div>`;$('#startAgain').onclick=resetAdvisor;$('#advisorFooter').style.display='none'}
  function renderAdvisor(){progress();if(state.stage==='questions')renderQuestions();else if(state.stage==='result')renderResult();else if(state.stage==='package')renderPackage();else renderSuccess();advisor.scrollTop=0}
  function resetAdvisor(){state.step=0;state.answers={};state.selectedProduct=null;state.weight=null;state.grind='beans';state.stage='questions';updateSaved();renderAdvisor()}
  function resetAll(){chat.innerHTML='';resetAdvisor();seedChat();setMode('chat')}
  function seedChat(){addMessage('Dobrý deň. Pomôžem vám vybrať kávu podľa chuti, kávovaru alebo nápoja, ktorý pijete najčastejšie.');setTimeout(()=>addMessage('Môžete sa opýtať priamo alebo spustiť výber cez štyri krátke otázky.'),180)}
  $('#heroOpen').onclick=openWidget;$('#openWidget').onclick=openWidget;$('#launcherLabel').onclick=openWidget;$('#closeWidget').onclick=closeWidget;$('#resetAll').onclick=resetAll;$('#openAdvisor').onclick=()=>setMode('advisor');$$('.mode__button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#chatForm').onsubmit=e=>{e.preventDefault();sendChat($('#chatInput').value)};
  prev.onclick=()=>{if(state.stage!=='questions'){state.stage='questions';state.step=3}else if(state.step>0)state.step--;renderAdvisor()};next.onclick=()=>{if(!state.answers[questions[state.step].key])return;if(state.step<3)state.step++;else state.stage='result';renderAdvisor()};
  renderChips();seedChat();renderAdvisor();setTimeout(()=>$('#launcherLabel').style.opacity='1',500);
})();
